(ns euler002
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.")

(defn even-fibonacci-helper [nums left right max]
  (if (>= left max)
    nums
    (recur (if (even? left) (cons left nums) nums) right (+ left right) max)))

(defn- even-fibonacci [max]
  (even-fibonacci-helper [] 0 1 max))

(defn solve [n]
  (apply + (even-fibonacci n)))

(println (solve 4000000))
